#!/bin/bash
f(){ sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p";}
L=$(curl -s ipinfo.io/json);c=$(f city<<<"$L");k=$(f country<<<"$L")
j=$(curl -sL "https://api.aladhan.com/v1/timingsByCity?city=${c// /%20}&country=$k&method=17")
for p in Fajr:Subuh Dhuhr:Zohor Asr:Asar Maghrib:Maghrib Isha:Isyak;do
printf "%-8s %s\n" ${p#*:} $(f ${p%:*}<<<"$j")
done
